### ISSUE TITLE
Not selecting a cluster leads to a stack trace

### ISSUE THREAD

**Issue by m3adow** [lauraseidler/kubeseal-ui#1]
Steps to reproduce:

1. Have more than one cluster (maybe not required?)
2. Don't select any
3. Try to seal a new secret

Result:

An error page with this content:

```
Error: Invariant failed
    at invariant (/srv/node_modules/tiny-invariant/dist/tiny-invariant.cjs.js:10:15)
    at action (/srv/build/index.js:501:37)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.callRouteAction (/srv/node_modules/@remix-run/server-runtime/data.js:36:14)
    at async handleDataRequest (/srv/node_modules/@remix-run/server-runtime/server.js:110:18)
    at async requestHandler (/srv/node_modules/@remix-run/server-runtime/server.js:45:20)
    at async /srv/node_modules/@remix-run/express/server.js:45:22
```

Expected result:

Having some kind of in-site message that the cluster selection is required

**Comment by lauraseidler** [comment]
@m3adow indeed, thanks! fixed :)
